openapi: 3.0.0
info:
  title: URL Shortener API
  description: API for shortening URLs and redirecting to original URLs.
  version: 1.0.0

servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /shorten:
    post:
      summary: Shorten a URL
      description: Accepts an original URL and returns a shortened URL.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
                  example: "http://example.com"
      responses:
        '200':
          description: Shortened URL successfully created
          content:
            application/json:
              schema:
                type: object
                properties:
                  short_url:
                    type: string
                    example: "http://localhost:5000/abcd1234"
        '400':
          description: Invalid input

  /{short_url}:
    get:
      summary: Redirect to original URL
      description: Redirects to the original URL based on the shortened URL.
      parameters:
        - name: short_url
          in: path
          required: true
          schema:
            type: string
            example: "abcd1234"
      responses:
        '302':
          description: Redirects to the original URL
        '404':
          description: Shortened URL not found

components:
  schemas:
    URL:
      type: object
      properties:
        original_url:
          type: string
          description: The original URL before shortening
        short_url:
          type: string
          description: The shortened URL